name: Build and Publish sdist

on:
  # push:
  #   branches: [ "Master" ]
  #   tags:
  #     - 'v*'
  # pull_request:
  #   branches: [ "Master" ]
  workflow_dispatch:

jobs:
        
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
        
    - name: Build sdist
      run: |
        python -m pip install -U pip build
        python -m build --sdist -Csetup-args=-Dallow-noblas=true
        
    - name: Check README rendering for PyPI
      run: |
        python -mpip install twine
        twine check dist/*     
        
    - uses: actions/upload-artifact@v3
      with:
        path: ./dist/*
    
  upload_pypi:
    needs: [build_wheels]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: artifact
        path: dist
    
    - name: List Build contents
      run: ls -l dist
      
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_TOKEN }}
        skip_existing: true
        
