name: Create Release

on:
  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel

    - name: Get version from pyproject.toml
      id: get_version
      run: |
        VERSION=$(python -c "import toml; print(toml.load('pyproject.toml')['tool.poetry']['version'])")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create tag
      run: |
        git tag v${{ env.VERSION }}
        git push origin v${{ env.VERSION }}

    - name: Build source distribution
      run: python setup.py sdist

    - name: Create ZIP archive of source code
      run: git archive -o source_code.zip HEAD

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: source-distribution
        path: dist/*.tar.gz

    - name: Upload source code ZIP
      uses: actions/upload-artifact@v3
      with:
        name: source-code-zip
        path: source_code.zip
